### ISSUE TITLE
Lab 6 - Recommended Duration

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-201-Designing-an-Azure-Data-Solution#13]
This one needs to be adjusted, because it's inconsistent:

A) At the top of the lab the total duration is stated at 60 minutes
B) The lab itself has 3 exercises of 15 minutes each, for a total of 45 minutes

It seems from (B) that the correct duration for the lab should be 45 minutes - i.e. (A) should be adjusted.

**Comment by ctesta-oneillmsft** [comment]
changed. Thanks
