### ISSUE TITLE
Solutions seem to be accidentally provided in DP-201-Lab03_Ex02_Ta01

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-201-Designing-an-Azure-Data-Solution#15]
This is inconsistent with all other files in Starter folder, which are designed to contain templates for students to fill out. It also deviates from instructions for this Lab and overall just looks like a copy & paste error.

![image](https://user-images.githubusercontent.com/1765732/69924773-14c1ce80-147b-11ea-95dc-e5bd716ad6d7.png)

**Comment by ctesta-oneillmsft** [comment]
Thanks. resolved
