### ISSUE TITLE
Files in \Starter folder contain many issues and require editing

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-201-Designing-an-Azure-Data-Solution#16]
There are many editing errors in these files. This causes a lot of student confusion. The students have trouble following steps and matching files to instructions as a result. 

Recommend that Microsoft reviews all Word files in the Starter folder and addresses the issues. 

Example of two such issues:

![image](https://user-images.githubusercontent.com/1765732/69925122-877f7980-147c-11ea-8e21-ac7434045a65.png)

**Comment by vitaly-livshits** [comment]
Second annotation in my screenshot got cut off. The full text should say "Does not match file. Also does not match instruction steps on GitHub".

**Comment by ctesta-oneillmsft** [comment]
resolved
