### ISSUE TITLE
Request solution files for the labs

### ISSUE THREAD

**Issue by HenrryVargas** [MicrosoftLearning/DP-201-Designing-an-Azure-Data-Solution#18]
Hi

Can you add solutions example for the labs?

It more easy compare the work done with the solutions and know if the lab is done correct.

Thanks!.

**Comment by ilikesql** [comment]
Hi @HenrryVargas, 

We will take this under consideration as we are planning for a broader and needed future content update (still in planning), as it relates to changes in the Data Engineer role as well as the evolution of Azure Synapse Analytics.
