### ISSUE TITLE
Lab 2 Filenames and Paths Point to Lab 1

### ISSUE THREAD

**Issue by davidcwalls** [MicrosoftLearning/DP-201-Designing-an-Azure-Data-Solution#19]
(I haven't found the Allfile.zip to confirm, but I am assuming its structure mirrors the folders here in GitHub) 

Ex 1 Task 1 references Allfiles\Labfiles\Starter\DP-201.**1**
should be Allfiles\Labfiles\Starter\DP-201.**2**

Ex 1 Task 2 references DP-201-**Lab01**_Ex01_Ta02.docx from the Allfiles\Labfiles\Starter\DP-201.**1**
should be DP-201-**Lab02**_Ex01_Ta02.docx from the Allfiles\Labfiles\Starter\DP-201.**2**

Ex 2 Task 1 references DP-201-**Lab01**_Ex02_Ta01.docx from the Allfiles\Labfiles\Starter\DP-201.**1** 
should be DP-201-Lab02_Ex02_Ta01.docx from the Allfiles\Labfiles\Starter\DP-201.**2** 
(the filename is listed twice in this task)

Ex 3 Task 1 references DP-201-**Lab01**_Ex02_Ta01.docx from the Allfiles\Labfiles\Starter\DP-201.**2** 
should be DP-201-**Lab02**_Ex02_Ta01.docx from the Allfiles\Labfiles\Starter\DP-201.**2**

**Comment by ilikesql** [comment]
Hi David, we'll get this reviewed, something might have gone wrong with packaging. 
@ctesta-oneillmsft

**Comment by ctesta-oneillmsft** [comment]
Hi @davidcwalls 

PLease can you confirm which lab

**Comment by davidcwalls** [comment]
Instructions for Lab 2 Ex 1 Task 1 Step 1:
From your machine, start Microsoft Word, and open up the file DP-201-Lab02_Ex01_Ta01.docx from the Allfiles\Labfiles\Starter\DP-201.1 folder.

I believe it should read:
From your machine, start Microsoft Word, and open up the file DP-201-Lab02_Ex01_Ta01.docx from the Allfiles\Labfiles\Starter\DP-201.2 folder.

**Comment by davidcwalls** [comment]
Instructions for Lab 2 Ex 1 Task 2 Step 1:
From your machine, start Microsoft Word, and open up the file DP-201-Lab01_Ex01_Ta02.docx from the Allfiles\Labfiles\Starter\DP-201.1 folder.

Seems like it should be:
From your machine, start Microsoft Word, and open up the file DP-201-Lab02_Ex01_Ta02.docx from the Allfiles\Labfiles\Starter\DP-201.2 folder.

**Comment by ctesta-oneillmsft** [comment]
Thanks. I have updated the references
