### ISSUE TITLE
dp-201-06_instructions same heading for all the 3 exercises

### ISSUE THREAD

**Issue by Derekp20** [MicrosoftLearning/DP-201-Designing-an-Azure-Data-Solution#2]
The dp-201-06_instructions have the same task heading for all 3 exercises.

Ex1 Task 1 is correct

EX 2 Task 1 "Draft a monitoring and analytics strategy that should be adopted by AdventureWorks"

Ex 3 Task 1 "1.	List the options for automation languages and approaches"

**Comment by ctesta-oneillmsft** [comment]
Thakns for your feedback @Derekp20
