### ISSUE TITLE
Dp 201.4  and .5 incorrect file names

### ISSUE THREAD

**Issue by Derekp20** [MicrosoftLearning/DP-201-Designing-an-Azure-Data-Solution#3]
The files in the DP 201.4 and DP 201.5 starter folders contain files that have "answer" as part of the name.

Remove _answer from the file names

Remove "Below are some examples of the requirements that could be identified." from the starter files.

**Comment by ctesta-oneillmsft** [comment]
Thanks for this feedback which has been actioned
