### ISSUE TITLE
Students requesting solution file here

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/DP-201-Designing-an-Azure-Data-Solution#4]
Can we share MCT downloaded solution files or can you include them in LabFiles?

**Comment by ctesta-oneillmsft** [comment]
The instructor should share the solutions with the students that **attend the class** by design . If you give the students the answers before doing the labs, they tend not to think about the problems they are trying to solve, ans rely on the answer key for help. that is not the intention.
