### ISSUE TITLE
Some lab instructions reference an incorrect course number (DP-200)

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-201-Designing-an-Azure-Data-Solution#8]
There are many references to DP-200, which is of course a completely different course. See screenshot below for one example:

![image](https://user-images.githubusercontent.com/1765732/69685173-7b18ac80-1089-11ea-9d45-b5e5e73cd11f.png)

**Comment by ctesta-oneillmsft** [comment]
resolved. Thanks
