### ISSUE TITLE
References to Azure SQL DW

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-201-Designing-an-Azure-Data-Solution#9]
As we know Microsoft renamed Azure SQL DW to Azure Synapse Analytics at Ignite 2019.  The docs.microsoft.com site has been synced up with this change, as has various Azure documentation.

Similarly, various elements of the lab (and course itself) should be updated as well. This is especially important because students new to Azure may be unfamiliar with legacy product names.

**Comment by ctesta-oneillmsft** [comment]
replaced
